version: "3.7"

services:

  db:
    container_name: $DB_CONTAINER_NAME
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - "$DB_PORT:3306"
    volumes:
      - ./db/mysql/config:/etc/mysql/mysql.conf.d$CACHED

  web:
    container_name: $WEB_CONTAINER_NAME
    image: $WEB_IMAGE
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - .:/var/www/html$CACHED
      - /var/www/html/var/
      - /var/www/html/public/typo3temp/
    environment:
      - USERID=$WEB_USERID
      - GROUPID=$WEB_GROUPID

      - WEB_CONTAINER_NAME=$WEB_CONTAINER_NAME

      - DB_CONTAINER_NAME=$DB_CONTAINER_NAME
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD

    command: "sh /var/www/html/docker_config/run.sh"
