db:
  type: mysql:10.4
  disk: 2048
cache:
  type: redis:5.0
# -SOLR- uncomment if using solr
# solrsearch:
#     type: solr:8.4
#     disk: 1024
#     configuration:
#       configsets:
#         mainconfig: !archive "configsets/ext_solr_11_0_0"
#       cores:
#         core_main:
#           core_properties: |
#             configSet=mainconfig
#             schema=swedish/schema.xml
#         core_site2:
#           core_properties: |
#             configSet=mainconfig
#             schema=english/schema.xml
#       endpoints:
#         main:
#           core: core_main
#         site2:
#           core: core_site2
