db:
  type: mysql:10.4
  disk: 2048
cache:
  type: redis:5.0
# -SOLR- uncomment if using solr
# solrsearch:
#     type: solr:8.4
#     disk: 1024
#     configuration:
#       configsets:
#         mainconfig: !archive "configsets/ext_solr_11_0_0"
#       cores:
#         core_sv:
#           core_properties: |
#             configSet=mainconfig
#             schema=swedish/schema.xml
#         core_en:
#           core_properties: |
#             configSet=mainconfig
#             schema=english/schema.xml
#       endpoints:
#         swedish:
#           core: core_sv
#         english:
#           core: core_en
