version: "3.7"

services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: ${DB_IMAGE:-mariadb:10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: ${WEB_IMAGE:-t3kit/10-php7.4-apache2.4-buster:1.1.1}
    environment:
      - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/local}

      - DB_HOST=${COMPOSE_PROJECT_NAME}_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
      - DB_NAME=${DB_NAME:-t3kit10}
      - DB_USER=${DB_USER:-root}

      - USER_ID=${USER_ID:-1000}
    volumes:
      - ../../:/var/www/html${FILE_SYSTEM_MODE:-:delegated}
      - typo3temp:/var/www/html/public/typo3temp/
      - var:/var/www/html/var/
      - t3kit_vendor:/var/www/html/public/typo3conf/ext/t3kit/build/
      - t3kit_node_modules:/var/www/html/public/typo3conf/ext/t3kit/node_modules/

networks:
  default:
    external:
      name: nproxy

volumes:
  typo3temp:
    name: ${COMPOSE_PROJECT_NAME}_typo3temp
  var:
    name: ${COMPOSE_PROJECT_NAME}_var
  db:
    name: ${COMPOSE_PROJECT_NAME}_db
  t3kit_node_modules:
    name: ${COMPOSE_PROJECT_NAME}_t3kitnodemodules
  t3kit_vendor:
    name: ${COMPOSE_PROJECT_NAME}_t3kitvendor
