version: "3.7"

services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: ${DB_IMAGE:-mysql:5.7}
    command:
      - --disable-log-bin
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

      - --sql_mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      - --query_cache_size=0
      - --query_cache_type=0
      - --query_cache_limit=2097152
      - --innodb_log_file_size=16M
      - --innodb_flush_log_at_trx_commit=0
      - --innodb_flush_method=O_DIRECT
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-1234}

  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: ${WEB_IMAGE:-t3kit/ubuntu18.04-php7.2-apache:1.2.1}
    environment:
      - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.${LOCALHOST_TOP_DOMAIN:-local}
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/local}

      - DB_HOST=${COMPOSE_PROJECT_NAME}_db
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-1234}
      - DB_NAME=${DB_NAME:-t3kit9}
      - DB_USER=${DB_USER:-root}

      - USERID=${USERID:-}
    volumes:
      - ../../:/var/www/html${CACHED:-}

networks:
  default:
    external:
      name: nproxy
