# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: php:7.4
build:
  flavor: composer

runtime:
  request_terminate_timeout: 240
  sizing_hints:
    request_memory: 20
  extensions:
    - redis

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: 'db:mysql'
  rediscache: 'cache:redis'

# The configuration of app when it is exposed to the web.
web:
  locations:
    '/':
      # The public directory of the app, relative to its root.
      # check if web convention
      root: 'public'
      passthru: '/index.php'
      index:
        - 'index.php'
      allow: false
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|html|map|ico|bmp|eot|woff2?|otf|ttf|webmanifest|xsl)$':
          allow: true
          passthru: false
          expires: 1M
        '\.(css|js)$':
          allow: true
          passthru: false
          expires: 1y
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true
        '/(wp-login\.php|wp-login|login\.php|wp-content|wp-admin|wp-cofigs\.php|wp-pot\.php|wp-404\.php|xmlrpc\.php|wp-load\.php|wp-json|cgi|CGI|home\.php|seo-joy\.cgi|light\.cgi|gastenboek\.php|bbs\.cgi|aska\.cgi|jax_guestbook\.php|wp/|phpmyadmin|phpMyAdmin|pma|sql|default\.htm|backup|bitcoin|admin\.php)':
          passthru: false
          allow: false
        '(/tel:|test\.php|modules\.php|install\.php|autodiscover\.xml)':
          passthru: false
          allow: false
        '\.(asp|aspx|esp|cgi|dat)$':
          passthru: false
          allow: false
    '/fileadmin':
      root: 'public/fileadmin'
      expires: 1M
      scripts: false
      allow: true
    '/typo3temp/assets':
      root: 'public/typo3temp/assets'
      expires: 1M
      scripts: false
      allow: true
      passthru: false
      rules:
        '\.js\.gzip$':
          expires: 1m
          headers:
            Content-Type: text/javascript
            Content-Encoding: gzip
        '\.css\.gzip$':
          expires: 1m
          headers:
            Content-Type: text/css
            Content-Encoding: gzip
    '/typo3conf/LocalConfiguration.php':
      allow: false
    '/typo3conf/AdditionalConfiguration.php':
      allow: false

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
  "public/typo3temp":
    source: local
    source_path: "typo3temp"
  "public/fileadmin":
    source: local
    source_path: "fileadmin"
  "var":
    source: local
    source_path: "var"

# The hooks that will be performed when the package is deployed.
hooks:
  build: |
    set -e

    # Install the CLI on a Platform.sh environment
    curl -sS https://platform.sh/cli/installer | php

    if [ -f public/typo3conf/LocalConfiguration.php ]; then
        mv public/typo3conf/LocalConfiguration.php public/typo3conf/LocalConfiguration.FromSource.php
        ln -sf ../../var/LocalConfiguration.php public/typo3conf/LocalConfiguration.php
    fi;

  deploy: |
    set -e

    cp public/typo3conf/LocalConfiguration.FromSource.php var/LocalConfiguration.php

crons:
  typo3scheduler:
    # run at every 7th minute
    spec: "*/7 * * * *"
    cmd: "vendor/bin/typo3 scheduler:run"
  backup:
    # Take a backup automatically every night at 2 am (UTC).
    spec: '0 2 * * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        platform backup:create --yes --no-wait
      fi
  renewcert:
    # Force a redeploy at 5 am (UTC) on the 1st and 15th of every month.
    spec: '0 5 1,15 * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        platform redeploy --yes --no-wait
      fi
