base: '%env(PLATFORM_ROUTES_MAIN)%'
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\n\r\nDisallow: /typo3/\r\nDisallow: /typo3conf/\r\nAllow: /typo3conf/ext/\r\n\r\n# sitemap\r\nSitemap: https://%env(PLATFORM_ROUTES_MAIN)%/sitemap.xml"
