name: Code Guidelines
# https://github.com/t3kit/.github/blob/master/CONTRIBUTING.md#coding-rules

on: [push, pull_request]

jobs:


  build-composer:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint shell scripts with Shellcheck
        run: shellcheck -e SC1091 .localconf/**/*.sh

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Composer version
        run: composer --version

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run default Composer lint tests
        run: composer run-script test
